apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-helper
  labels:
    app: hugo-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo-helper
  template:
    metadata:
      labels:
        app: hugo-helper
    spec:
      containers:
      - name: hugo-helper
        image: hugo-helper:{{ .Commit }}
        imagePullPolicy: IfNotPresent